{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
  name: "{{ .name }}"
  namespace: {{ .namespace }}
spec:
  refreshInterval: {{ $.Values.global.refreshInterval}}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRefKey }}
    {{- if .remoteRefProperty }}
        property: {{ .remoteRefProperty }}
    {{- end }}
    {{- end }}
  secretStoreRef:
    name: {{ $.Values.global.clusterSecretStore}}
    kind: ClusterSecretStore
  target:
    name: {{ .targetSecretName }}
{{- end }}