---
global:
  clusterSecretStore: cluster-secrets-store
  refreshInterval: 24h0m0s

externalSecrets:
  - name: backstage-github-authentication
    namespace: platform
    targetSecretName: backstage-github-authentication
    data:
      - secretKey: AUTH_GITHUB_CLIENT_ID
        remoteRefKey: github-client-id
      - secretKey: AUTH_GITHUB_CLIENT_SECRET
        remoteRefkey: github-client-secret
      - secretKey: GITHUB_TOKEN
        remoteRefkey: github-token
  - name: backstage-kubernetes-authentication
    namespace: platform
    targetSecretName: backstage-kubernetes-authentication
    data:
      - secretKey: K8S_TOKEN
        remoteRefkey: kubernetes-tooling-token
      - secretKey: K8S_URL
        remoteRefkey: kubernetes-tooling-token-url
  - name: backstage-database-authentication
    namespace: platform
    targetSecretName: backstage-database-authentication
    data:
      - secretKey: POSTGRES_USER
        remoteRefkey: backstage-postgres-user
      - secretKey: POSTGRES_PASSWORD
        remoteRefkey: backstage-postgres-password
      - secretKey: POSTGRES_PORT
        remoteRefkey: backstage-postgres-port